# Site settings
title: 5am	
email: anothersamchan@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /samchan.github.io
twitter_username: anothersamchan
github_username:  samchan
facebook_username:  samchan

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]